package cn.itcast.ssm.po;

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

public class Items {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMS.ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMS.NAME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMS.PRICE
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMS.DETAIL
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMS.PIC
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMS.CREATETIME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMS.ID
     *
     * @return the value of ITEMS.ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMS.ID
     *
     * @param id the value for ITEMS.ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMS.NAME
     *
     * @return the value of ITEMS.NAME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMS.NAME
     *
     * @param name the value for ITEMS.NAME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMS.PRICE
     *
     * @return the value of ITEMS.PRICE
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMS.PRICE
     *
     * @param price the value for ITEMS.PRICE
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMS.DETAIL
     *
     * @return the value of ITEMS.DETAIL
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMS.DETAIL
     *
     * @param detail the value for ITEMS.DETAIL
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMS.PIC
     *
     * @return the value of ITEMS.PIC
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMS.PIC
     *
     * @param pic the value for ITEMS.PIC
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMS.CREATETIME
     *
     * @return the value of ITEMS.CREATETIME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMS.CREATETIME
     *
     * @param createtime the value for ITEMS.CREATETIME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}