package cn.itcast.ssm.po;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.USER_ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.SNO
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CREATETIME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.NOTE
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ID
     *
     * @return the value of ORDERS.ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ID
     *
     * @param id the value for ORDERS.ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.USER_ID
     *
     * @return the value of ORDERS.USER_ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.USER_ID
     *
     * @param userId the value for ORDERS.USER_ID
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.SNO
     *
     * @return the value of ORDERS.SNO
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.SNO
     *
     * @param sno the value for ORDERS.SNO
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CREATETIME
     *
     * @return the value of ORDERS.CREATETIME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CREATETIME
     *
     * @param createtime the value for ORDERS.CREATETIME
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.NOTE
     *
     * @return the value of ORDERS.NOTE
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.NOTE
     *
     * @param note the value for ORDERS.NOTE
     *
     * @mbggenerated Tue Dec 05 15:43:05 GMT+08:00 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}